#! /bin/sh

$HOME/.config/polybar/launch.sh
pgrep -x sxhkd > /dev/null || sxhkd &

#Loading compton compositor
compton &

#Setting the wallpaper on startup
nitrogen --restore &
#nitrogen --set-scaled walla.jpg

#Loading Xresources config
xrdb -load ~/.config/.Xresources

#Setting screen resolution for desktop on startup
xrandr -s 1360x768

#Setting number of screens
bspc monitor -d I

#Drag and resize floating windows
bspc config pointer_modifier		control


#bspwm theming
bspc config border_width         	2
bspc config window_gap          	5

bspc config split_ratio          	0.52
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config top_padding		 	20
bspc config bottom_padding	 	0
bspc config left_padding	 	0
bspc config right_padding 	 	0
bspc config focus_by_distance	 	true
bspc config split_ratio 	 	0.50
bspc config single_monocle 	 	false
bspc config gapless_monocle	 	true
bspc config borderless_monocle	 	true
bspc config focus_follows pointer	true
bspc config history_aware_focus		true
bspc config pointer_action1 mod4
bspc config pointer_action2 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#BSPWM coloring
bspc config normal_border_color			"#4c566a"
bspc config active_border_color			"#lelele"
bspc config focused_border_color		"#5e81ac"
bspc config presel_feedback_color		"#5e81ac"
bspc config urgent_border_color			"#dd2727"
